AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy parlpod to AWS"
Resources:
  ParlpodLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content:
        S3Bucket: parlpod.datapunch.net-dev-deployment
        S3Key: parlpod-dev.zip
      Description: Parlpod Layer
      LayerName: parlpod-layer
  ParlpodGetList:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: parlpod.datapunch.net-dev-deployment
        S3Key: parlpod-dev.zip
      Description: String
      Environment:
        Variables:
          BUCKET_NAME: dev-parlpod.datapunch.net
          HTTP_PREFIX: http://dev-parlpod.datapunch.net.s3.amazonaws.com
      FunctionName: ParlpodGetList
      Handler: parlpod.lambda_get_list
      MemorySize: 1024
      Role: arn:aws:iam::703961766271:role/ParlpodServiceRole
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: Active
  ParlpodDownload:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: parlpod.datapunch.net-dev-deployment
        S3Key: parlpod-dev.zip
      Description: String
      Environment:
        Variables:
          BUCKET_NAME: dev-parlpod.datapunch.net
          HTTP_PREFIX: http://dev-parlpod.datapunch.net.s3.amazonaws.com
      FunctionName: ParlpodDownload
      Handler: parlpod.lambda_download
      MemorySize: 1024
      Role: arn:aws:iam::703961766271:role/ParlpodServiceRole
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: Active
  ParlpodCreateRss:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: parlpod.datapunch.net-dev-deployment
        S3Key: parlpod-dev.zip
      Description: String
      Environment:
        Variables:
          BUCKET_NAME: dev-parlpod.datapunch.net
          HTTP_PREFIX: http://dev-parlpod.datapunch.net.s3.amazonaws.com
      FunctionName: ParlpodCreateRss
      Handler: parlpod.lambda_create_rss
      MemorySize: 1024
      Role: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodServiceRole" }
      Runtime: python3.6
      Timeout: 900
      TracingConfig:
        Mode: Active
  ParlpodStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          |-
            {
                "Comment": "Parlpod State Machine",
                "StartAt": "ParlpodGetListState",
                "States": {

                    "ParlpodGetListState": {
                        "Type": "Task",
                        "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ParlpodGetList",
                        "Next": "ParlpodDownloadState"
                    },
                    "ParlpodDownloadState": {
                        "Type": "Task",
                        "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ParlpodDownload",
                        "Next": "IsFinished"
                    },
                    "IsFinished": {
                        "Type": "Choice",
                        "Choices": [
                            {
                                "Variable": "$.done",
                                "BooleanEquals": false,
                                "Next": "ParlpodDownloadState"
                            }
                        ],
                        "Default": "Done"
                    },
                    "Done": {
                        "Type": "Pass",
                        "End": true

                    }
                }
            }
      RoleArn: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodStatesRole" }