AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy parlpod to AWS"
Resources:
  ParlpodSchedule:
    Type: AWS::Events::Rule
    Properties:
      #ScheduleExpression: "cron(0 * * * ? *)"
      ScheduleExpression: "cron(0 02 * * ? *)"
      State: ENABLED
      Targets: [ {
        "Arn": {"Fn::Sub": "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:ParlpodStateMachine"},
        "Id": ParlpodStateMachine,
        "RoleArn": { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodScheduleRole" }
      } ]

