AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy parlpod to AWS"
Parameters:
  ParlpodBucketnameParameter:
    Type: String
    Default: dev-parlpod.datapunch.net
  ParlpodUrlParameter:
    Type: String
    Default: http://dev-parlpod.datapunch.net/
  ParlpodDeploymentBucketnameParameter:
    Type: String
    Default: parlpod.datapunch.net-dev-deployment
  ParlpodDeploymentKeyParameter:
    Type: String
    Default: parlpod-dev.zip
Resources:
  ParlpodLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: {Ref: ParlpodDeploymentBucketnameParameter}
        S3Key: {Ref: ParlpodDeploymentKeyParameter}
      Description: Parlpod Layer
      LayerName: parlpod-layer
  ParlpodGetList:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: {Ref: ParlpodDeploymentBucketnameParameter}
        S3Key: {Ref: ParlpodDeploymentKeyParameter}
      Description: String
      Environment:
        Variables:
          BUCKET_NAME: {Ref: ParlpodBucketnameParameter}
          HTTP_PREFIX: {Ref: ParlpodUrlParameter}
      FunctionName: ParlpodGetList
      Handler: parlpod.lambda_get_list
      MemorySize: 1024
      Role: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodServiceRole" }
      Runtime: python3.7
      Timeout: 900
      TracingConfig:
        Mode: Active
  ParlpodDownload:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: {Ref: ParlpodDeploymentBucketnameParameter}
        S3Key: {Ref: ParlpodDeploymentKeyParameter}
      Description: String
      Environment:
        Variables:
          BUCKET_NAME: {Ref: ParlpodBucketnameParameter}
          HTTP_PREFIX: {Ref: ParlpodUrlParameter}
      FunctionName: ParlpodDownload
      Handler: parlpod.lambda_download
      MemorySize: 1024
      Role: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodServiceRole" }
      Runtime: python3.7
      Timeout: 900
      TracingConfig:
        Mode: Active
  ParlpodCreateRss:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: {Ref: ParlpodDeploymentBucketnameParameter}
        S3Key: {Ref: ParlpodDeploymentKeyParameter}
      Description: String
      Environment:
        Variables:
          BUCKET_NAME: {Ref: ParlpodBucketnameParameter}
          HTTP_PREFIX: {Ref: ParlpodUrlParameter}
      FunctionName: ParlpodCreateRss
      Handler: parlpod.lambda_create_rss
      MemorySize: 1024
      Role: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodServiceRole" }
      Runtime: python3.7
      Timeout: 900
      TracingConfig:
        Mode: Active
  ParlpodStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: ParlpodStateMachine
      DefinitionString:
        !Sub
          |-
            {
                "Comment": "Parlpod State Machine",
                "StartAt": "ParlpodGetListState",
                "States": {

                    "ParlpodGetListState": {
                        "Type": "Task",
                        "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ParlpodGetList",
                        "Next": "ParlpodDownloadState"
                    },
                    "ParlpodDownloadState": {
                        "Type": "Task",
                        "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ParlpodDownload",
                        "Next": "IsFinished"
                    },
                    "IsFinished": {
                        "Type": "Choice",
                        "Choices": [
                            {
                                "Variable": "$.done",
                                "BooleanEquals": false,
                                "Next": "ParlpodDownloadState"
                            }
                        ],
                        "Default": "ParlpodCreateRss"
                    },
                    "ParlpodCreateRss": {
                        "Type": "Task",
                        "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ParlpodCreateRss",
                        "Next": "Done"
                    },

                    "Done": {
                        "Type": "Pass",
                        "End": true

                    }
                }
            }
      RoleArn: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/ParlpodStatesRole" }