AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy parlpod roles to AWS"
Parameters:
  ParlpodBucketnameParameter:
    Type: String
    Default: dev-parlpod.datapunch.net
Resources:
  ParlpodServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ParlpodServiceRole"
      Policies:
        -
          PolicyName: "ParlpodServicePolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:PutAccountPublicAccessBlock
                  - s3:GetAccountPublicAccessBlock
                  - xray:PutTelemetryRecords
                  - s3:ListAllMyBuckets
                  - s3:HeadBucket
                  - xray:CreateGroup
                  - logs:CreateLogGroup
                  - xray:PutTraceSegments
                Resource: "*"
              - Sid: VisualEditor1
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:log-group:*
              -
                Effect: Allow
                Action: logs:PutLogEvents
                Resource: arn:aws:logs:*:*:log-group:*:*:*
              -
                Effect: Allow
                Action: s3:*
                Resource:
                  - {"Fn::Join": ["", ["arn:aws:s3:::", {Ref: ParlpodBucketnameParameter}]]}
                  - {"Fn::Join": ["", ["arn:aws:s3:::", {Ref: ParlpodBucketnameParameter}, "/*"]]}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  ParlpodStatesRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ParlpodStatesRole"
      Policies:
        -
          PolicyName: ParlpodStatesPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - "arn:aws:lambda:::function:Parlpod*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "stepfunctions.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  ParlpodScheduleRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ParlpodScheduleRole"
      Policies:
        -
          PolicyName: ParlpodSchedulePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - states:DescribeStateMachineForExecution
                - states:DescribeStateMachine
                - states:DescribeExecution
                - states:ListExecutions
                - states:GetExecutionHistory
                - states:StartExecution
                - states:ListTagsForResource
                Resource:
                - arn:aws:states:*:*:execution:ParlpodStateMachine:*
                - arn:aws:states:*:*:stateMachine:ParlpodStateMachine
              - Effect: Allow
                Action: states:ListStateMachines
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudwatchevents.amazonaws.com"
            Action:
              - "sts:AssumeRole"
